"""Typed contracts shared by local SQLite and remote PostgreSQL repositories."""

from typing import Any, Protocol

from app.business.requests import RequestKind
from app.persistence.sqlite import Customer, User


class PersistenceUnavailable(RuntimeError):
    def __init__(self) -> None:
        super().__init__("El almacenamiento no está disponible. Prueba de nuevo más tarde.")


class IdentityStore(Protocol):
    @property
    def jwt_secret(self) -> bytes: ...
    def setup_required(self) -> bool: ...
    def get_user(self, user_id: str) -> User | None: ...
    def get_user_by_email(self, email: str) -> User | None: ...
    def bootstrap_admin(self, name: str, email: str, password_hash: str) -> User: ...
    def register_customer(self, name: str, email: str, password_hash: str) -> User: ...
    def get_customer(self, user_id: str) -> Customer | None: ...
    def list_customers(self, limit: int = 25, offset: int = 0) -> tuple[list[Customer], int]: ...
    def create_session(self, user_id: str, refresh_token: str) -> str: ...
    def session_user(self, session_id: str, user_id: str) -> User | None: ...
    def rotate_refresh(self, previous: str, replacement: str) -> tuple[User, str] | None: ...
    def revoke_session(self, session_id: str, user_id: str | None = None) -> None: ...
    def revoke_refresh(self, refresh_token: str) -> None: ...
    def create_conversation(self, user_id: str, session_id: str | None, title: str) -> str: ...
    def conversation_history(self, user_id: str, identifier: str) -> list[dict[str, str]]: ...
    def save_exchange(
        self, user_id: str, identifier: str, message: str, response: dict[str, Any]
    ) -> None: ...
    def list_conversations(self, user_id: str) -> list[dict[str, Any]]: ...
    def delete_conversation(self, user_id: str, identifier: str) -> bool: ...
    def close(self) -> None: ...


class BusinessRepository(Protocol):
    def create_request(
        self,
        user_id: str,
        kind: RequestKind,
        details: dict[str, Any],
        action_key: str | None = None,
    ) -> dict[str, Any]: ...
    def list_requests(self, user_id: str, limit: int = 20) -> list[dict[str, Any]]: ...
    def list_all_requests(self, limit: int = 50) -> list[dict[str, Any]]: ...
    def close(self) -> None: ...
